version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/chaos.expert/FreifunkBremen/yanic
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go install -ldflags "-X chaos.expert/FreifunkBremen/yanic/cmd.VERSION=`git -C $GOPATH/src/chaos.expert/FreifunkBremen/yanic rev-parse HEAD`" chaos.expert/FreifunkBremen/yanic
      - store_artifacts:
          path: /go/bin/
          destination: yanic
  test:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/chaos.expert/FreifunkBremen/yanic
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go get github.com/mattn/goveralls
      - run: go get golang.org/x/tools/cmd/cover
      - run: ./.circleci/check-coverage
      - store_test_results:
          path: ./
          destination: profile.cov
      - run: ./.circleci/check-gofmt
      - run: ./.circleci/check-testfiles
  test_race:
    docker:
      - image: circleci/golang:latest
    working_directory: /go/src/chaos.expert/FreifunkBremen/yanic
    steps:
      - checkout
      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go test -race ./...
workflows:
  version: 2
  build_and_tests:
    jobs:
      - build
      - test
      - test_race
